In [49]:
import streamlit as st
import pandas as pd
import numpy as np
import snowflake.connector

In [12]:
from compare import compare_results

In [92]:
con_admin = snowflake.connector.connect(
    account="HU82657.us-central1.gcp",
    user="KSENII2",
    password="zTUJdgsdxypRErSV7z5Y",
    database="sql_eval",
    schema='ECOM'
)
cur = con_admin.cursor()
#pd.read_sql_query('show tables', con=con_admin)

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [ ]:
pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3334734221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from  AFFILIATE_NETWORKS limit 1', con=con_admin, params={'schema': 'coupon_platform'})

DatabaseError: Execution failed on sql 'select * from  AFFILIATE_NETWORKS limit 1': 002003 (42S02): SQL compilation error:
Object 'AFFILIATE_NETWORKS' does not exist or not authorized.

In [63]:
bench_df = pd.read_excel(r'data/benchmark_dataset_v2.xlsx')

In [89]:
bench_df

,query_id,error_type,schema,sql,Unnamed: 4
0,8,id alias,COUPON_PLATFORM,"\nSELECT \n s.name AS store_name, \n c.c...",NaN
1,22,like case sensitivity,COUPON_PLATFORM,\nSELECT *\nFROM COUPONS\nWHERE TITLE ILIKE '%...,1.0
2,20,like case sensitivity,COUPON_PLATFORM,\nSELECT *\nFROM STORES\nWHERE NAME ILIKE '%ec...,1.0
3,21,like case sensitivity,COUPON_PLATFORM,\nSELECT *\nFROM STORES\nWHERE NAME ILIKE '%Lo...,1.0
4,11,unnecessary join fanout,COUPON_PLATFORM,"\nSELECT\n categoryid,\n AVG(averagesavings)...",1.0
...,...,...,...,...,...
76,29,ranking proportions,ECOM,WITH popular_product_reviews_facts AS ( \n S...,NaN
77,70,complex fanout,COUPON_PLATFORM,WITH store_facts AS (\n SELECT\n s.C...,NaN
78,65,aggregation math,COUPON_PLATFORM,WITH store_transaction_totals AS (\n SELECT...,NaN
79,1,aggregation math,COUPON_PLATFORM,WITH store_transaction_totals AS (\n SELECT...,NaN
80,2,aggregation math,COUPON_PLATFORM,WITH user_transaction_totals AS (\n SELECT\...,NaN

In [93]:
for i, r in bench_df.iterrows():
    if r['schema'] == 'ECOM':
        try:
            pd.read_sql_query(r['sql'], con=con_admin)
        except Exception as e:
            print(f"query_id={r['query_id']}: {e}")

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)
C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)
C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)
C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)
C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)
C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)
C:\Users\computer\AppData\Local\Temp\ipykernel_22672\249341220.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(r['sql'], con=con_admin)

In [64]:
bench_df.sql.value_counts()

sql
\nSELECT \n    s.name AS store_name, \n    c.code AS coupon_code, \n    c.id AS coupon_id, \n    SUM(t.commissionvalue) AS total_commissions\nFROM \n    stores s\nJOIN coupons c ON s.id = c.storeid\nJOIN transactions t ON c.id = t.couponid\nGROUP BY \n    s.name, c.code, c.id\n                                                                                                                                             1
SELECT\n  coalesce(ans.PROGRAM, 'no affiliate network'),\n  COUNT(*) AS store_count\nFROM STORES s\nLEFT JOIN AFFILIATE_PROGRAM_STORES ans ON s.AFFILIATENETWORKID = ans.ID\nGROUP BY 1;                                                                                                                                                                                                                                           1
SELECT\n  t.PRODUCTID,\n  SUM(COALESCE(t.COMMISSIONVALUE, 0)) AS total_sales\nFROM TRANSACTIONS t\nGROUP BY t.PRODUCTID;                                                                                                                                                                                                                                                                                                           1
SELECT\n  s.CATEGORYID,\n  SUM(t.ORDERTOTAL) AS total_orders_amount\nFROM TRANSACTIONS t\nJOIN STORES s ON t.ADID = s.ID\nGROUP BY s.CATEGORYID\nHAVING COUNT(*) > 5;                                                                                                                                                                                                                                                              1
SELECT\n  REGEXP_SUBSTR(n.EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') AS valid_email\nFROM NEWSLETTERS n;                                                                                                                                                                                                                                                                                                           1
                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
SELECT\n    p.category_id as category_id,\n    SUM(i.quantity * p.price) AS inventory_value\nFROM\n    inventory i\nJOIN products p ON i.product_id = p.id\nGROUP BY\n    p.category_id;\n                                                                                                                                                                                                                                         1
SELECT\n    l.user_id,\n    l.login_time,\n    a.action,\n    a.action_time\nFROM user_logins l\nJOIN user_actions a ON l.user_id = a.user_id\n    AND a.action_time BETWEEN l.login_time AND l.login_time + INTERVAL '1 hour';\n                                                                                                                                                                                                  1
SELECT\n    e.USERID,\n    e.TIME AS login_time,\n    ea.EVENTNAME AS action,\n    ea.TIME AS action_time\nFROM EVENTS e\nJOIN EVENTS ea ON e.USERID = ea.USERID\n    AND ea.TIME BETWEEN e.TIME AND e.TIME + INTERVAL '1 hour';                                                                                                                                                                                                   1
SELECT\n    e.USERID,\n    e.TIME as login_time,\n    e.EVENTNAME as action,\n    e.TIME as action_time\nFROM EVENTS e\nJOIN EVENTS a ON e.USERID = a.USERID\n    AND a.TIME BETWEEN e.TIME AND e.TIME + INTERVAL '1 hour';                                                                                                                                                                                                        1
WITH user_transaction_totals AS (\n    SELECT\n        t.USERID, \n        SUM(t.COMMISSIONVALUE * t.ORDERTOTAL) AS total_commission\n    FROM \n        TRANSACTIONS t\n    GROUP BY \n        t.USERID\n)\nSELECT \n    nl.HASSUBSCRIBED, \n    AVG(utt.total_commission) AS average_user_commission\nFROM \n    NEWSLETTERS nl\nJOIN user_transaction_totals utt ON nl.USERID = utt.USERID\nGROUP BY \n    nl.HASSUBSCRIBED;    1
Name: count, Length: 81, dtype: int64

a b
1 2
3 4


a b
1 2
3 4
1 2
3 4

In [30]:
import pandas as pd

# Creating two series with different names but identical values and index
series1 = pd.Series([1, 2, 3], name='Series1', index=[3,2,1])
series2 = pd.Series([1, 2, 2], name='Series2')

# Comparing the two series
values_equal = (series1.values == series2.values).all()

print(values_equal)

ValueError: operands could not be broadcast together with shapes (3,) (4,)

In [14]:
con = snowflake.connector.connect(
    account="HU82657.us-central1.gcp",
    user="KSENII2",
    password="zTUJdgsdxypRErSV7z5Y",
    database="sql_eval",
    #schema='coupon_platform'
)
cur = con.cursor()
pd.read_sql_query('select * from coupon_platform.cpc limit 10', con=con)

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\1656658924.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from coupon_platform.cpc limit 10', con=con)

,ID,ADGROUPNAME,AVERAGEPOSITION,CAMPAIGNNAME,CLICKS,COST,DATE,DESTINATIONURL,IMPRESSIONS
0,0,d,77.0,e,909,39.0,2002-03-27 05:25:45,a,339
1,1,j,94.0,f,445,66.0,1989-04-27 20:20:38,e,377
2,2,a,43.0,a,778,12.0,2000-01-22 11:39:25,f,71
3,3,d,95.0,j,683,76.0,2003-01-18 06:09:16,f,637
4,4,h,50.0,a,698,43.0,1972-02-20 13:45:50,b,881
5,5,h,51.0,d,773,36.0,2020-03-28 01:34:29,h,964
6,6,j,16.0,b,529,87.0,1982-10-23 12:06:47,g,884
7,7,f,23.0,g,319,67.0,1970-09-01 01:49:01,g,712
8,8,c,88.0,f,637,34.0,1987-11-27 01:18:46,a,121
9,9,c,36.0,f,297,85.0,1977-11-23 14:18:21,b,978

In [15]:
con_viewer = snowflake.connector.connect(
    account="HU82657.us-central1.gcp",
    user="READ_ONLY_BENCHMARK_USER",
    password="bHQDv7fHHgr3jSEA97qt",
    database="sql_eval",
    schema='coupon_platform'
)
pd.read_sql_query('select * from cpc limit 10', con=con_viewer)

C:\Users\computer\AppData\Local\Temp\ipykernel_22672\3013980756.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from cpc limit 10', con=con_viewer)

,ID,ADGROUPNAME,AVERAGEPOSITION,CAMPAIGNNAME,CLICKS,COST,DATE,DESTINATIONURL,IMPRESSIONS
0,0,d,77.0,e,909,39.0,2002-03-27 05:25:45,a,339
1,1,j,94.0,f,445,66.0,1989-04-27 20:20:38,e,377
2,2,a,43.0,a,778,12.0,2000-01-22 11:39:25,f,71
3,3,d,95.0,j,683,76.0,2003-01-18 06:09:16,f,637
4,4,h,50.0,a,698,43.0,1972-02-20 13:45:50,b,881
5,5,h,51.0,d,773,36.0,2020-03-28 01:34:29,h,964
6,6,j,16.0,b,529,87.0,1982-10-23 12:06:47,g,884
7,7,f,23.0,g,319,67.0,1970-09-01 01:49:01,g,712
8,8,c,88.0,f,637,34.0,1987-11-27 01:18:46,a,121
9,9,c,36.0,f,297,85.0,1977-11-23 14:18:21,b,978

In [16]:
new_df = pd.read_csv('data/generated_questions.csv')

In [17]:
corr_idx = [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 19, 20, 21, 22, 23, 24, 25, 26]
fake_benchmark = new_df.iloc[corr_idx][['question', 'correct_sql_query']].reset_index(drop=True)
fake_benchmark

,question,correct_sql_query
0,1. What are all the transactions associated wi...,SELECT *\nFROM TRANSACTIONS\nWHERE ID IN (\n\t...
1,2. Which transactions were influenced by affil...,SELECT *\nFROM TRANSACTIONS\nWHERE ID IN (\n\t...
2,1. What was the average cost per click in the ...,SELECT AVG(COST) \nFROM CPC \nWHERE DATE BETWE...
3,2. How does the average cost per click in June...,SELECT AVG(COST) \nFROM CPC \nWHERE DATE BETWE...
4,1. What are the details of the Summer Sale pro...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION = 'S...
5,2. Can you provide information about the coupo...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION = 'S...
6,1. Which coupons have descriptions containing ...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION REGE...
7,2. Are there any issues with the formatting of...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION REGE...
8,1. What is the average cost per click for the ...,SELECT CAST(COST AS FLOAT) / CLICKS\nFROM CPC\...
9,2. How does the cost per click vary for the 'S...,SELECT CAST(COST AS FLOAT) / CLICKS\nFROM CPC\...
10,1. Which coupons have the highest number of up...,"SELECT ID, COUPONID, CODE, DESCRIPTION, VOTESU..."
11,2. Can you provide a list of the top-rated cou...,"SELECT ID, COUPONID, CODE, DESCRIPTION, VOTESU..."
12,1. What proportion of coupons are featured?,SELECT\n CAST(SUM(CASE WHEN ISFEATURED = TRUE...
13,2. What proportion of coupons are staff picks?,SELECT\n CAST(SUM(CASE WHEN ISFEATURED = TRUE...
14,1. What is the most clicked ad group within ea...,"SELECT ID, ADGROUPNAME, CAMPAIGNNAME, CLICKS, ..."
15,2. Which destination URL received the highest ...,"SELECT ID, ADGROUPNAME, CAMPAIGNNAME, CLICKS, ..."
16,1. What is the ratio of featured coupons to to...,"SELECT\n AFFILIATE_NETWORKS.NAME,\n COUNT(CA..."
17,2. How does the proportion of featured coupons...,"SELECT\n AFFILIATE_NETWORKS.NAME,\n COUNT(CA..."
18,1. What is the proportion of staff picks for e...,"SELECT\n AFFILIATE_NETWORKS.NAME,\n COUNT(CA..."
19,2. How does the proportion of staff picks vary...,"SELECT\n AFFILIATE_NETWORKS.NAME,\n COUNT(CA..."

In [20]:
fake_benchmark.to_csv('data/fake_benchmark.csv', index=False)

In [18]:
fake_submission_df = fake_benchmark.copy()
fake_submission_df['submitted_sql'] = fake_submission_df['correct_sql_query'][:10].to_list() + new_df['correct_sql_query'][-10:].to_list()
fake_submission_df.drop(columns=['correct_sql_query'], inplace=True)
fake_submission_df

,question,submitted_sql
0,1. What are all the transactions associated wi...,SELECT *\nFROM TRANSACTIONS\nWHERE ID IN (\n\t...
1,2. Which transactions were influenced by affil...,SELECT *\nFROM TRANSACTIONS\nWHERE ID IN (\n\t...
2,1. What was the average cost per click in the ...,SELECT AVG(COST) \nFROM CPC \nWHERE DATE BETWE...
3,2. How does the average cost per click in June...,SELECT AVG(COST) \nFROM CPC \nWHERE DATE BETWE...
4,1. What are the details of the Summer Sale pro...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION = 'S...
5,2. Can you provide information about the coupo...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION = 'S...
6,1. Which coupons have descriptions containing ...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION REGE...
7,2. Are there any issues with the formatting of...,SELECT *\nFROM COUPONS\nWHERE DESCRIPTION REGE...
8,1. What is the average cost per click for the ...,SELECT CAST(COST AS FLOAT) / CLICKS\nFROM CPC\...
9,2. How does the cost per click vary for the 'S...,SELECT CAST(COST AS FLOAT) / CLICKS\nFROM CPC\...
10,1. Which coupons have the highest number of up...,SELECT * \nFROM TRANSACTIONS \nWHERE DETAILS L...
11,2. Can you provide a list of the top-rated cou...,SELECT * \nFROM TRANSACTIONS \nWHERE DETAILS L...
12,1. What proportion of coupons are featured?,SELECT\n COUNT(TRANSACTIONDATE) AS NUM_TRANSA...
13,2. What proportion of coupons are staff picks?,SELECT\n COUNT(TRANSACTIONDATE) AS NUM_TRANSA...
14,1. What is the most clicked ad group within ea...,SELECT *\nFROM COUPONS\nWHERE ID REGEXP_LIKE(C...
15,2. Which destination URL received the highest ...,SELECT *\nFROM COUPONS\nWHERE ID REGEXP_LIKE(C...
16,1. What is the ratio of featured coupons to to...,SELECT\n CAST(SUM(CASE WHEN ISSPECIALSALE THE...
17,2. How does the proportion of featured coupons...,SELECT\n CAST(SUM(CASE WHEN ISSPECIALSALE THE...
18,1. What is the proportion of staff picks for e...,"SELECT\n TO_CHAR(EXPIRATIONDATE, 'HH24') AS E..."
19,2. How does the proportion of staff picks vary...,"SELECT\n TO_CHAR(EXPIRATIONDATE, 'HH24') AS E..."

In [23]:
to_sub = fake_submission_df.copy()
to_sub.to_csv('data/sample_submission.csv', index=False)

In [21]:
fake_submission_df.to_csv('data/fake_submission_df.csv',  index=False)

In [8]:
from typing import Tuple

READONLY_CON = con_viewer

def try_run_query(sql: str) -> pd.DataFrame | str:
    try:
        return pd.read_sql_query(sql, con=READONLY_CON)
    except Exception as e:
        print('failed to execute')
        return e

def compare_queries(benchmark_sql: str, submission_sql: str) -> dict[str, bool|str]:
    benchmark_loc_df = try_run_query(benchmark_sql)
    submission_loc_df = try_run_query(submission_sql)
    # print(submission_loc_df)
    # print(isinstance(submission_loc_df, pd.DataFrame))
    if isinstance(submission_loc_df, pd.DataFrame):
        res = compare_results(
            df_true=benchmark_loc_df,
            df_pred=submission_loc_df
        )
        if res:
            return {'score': res, 'reason': 'No error'}
        else:
            return {'score': res, 'reason': 'Incorrect output'}
    else:
        return {'score': False, 'reason': f"Failed to execute: {submission_loc_df}"}

def execution_accuracy(benchmark: pd.DataFrame, submission_df: pd.DataFrame):
    merged = pd.merge(benchmark, submission_df, on='question', how='left')

    results = []
    for i, row in merged.iterrows():
        # print(row['correct_sql_query'])
        # print(row['submitted_sql'])
        score_dict = compare_queries(row['correct_sql_query'], row['submitted_sql'])
        score_dict['question'] = row['question']
        results.append(score_dict)
    
    return pd.merge(submission_df, pd.DataFrame(results), on='question')

In [14]:
results.to_sql??

Signature:
results.to_sql(
    name: 'str',
    con,
    *,
    schema: 'str | None' = None,
    if_exists: "Literal['fail', 'replace', 'append']" = 'fail',
    index: 'bool_t' = True,
    index_label: 'IndexLabel | None' = None,
    chunksize: 'int | None' = None,
    dtype: 'DtypeArg | None' = None,
    method: "Literal['multi'] | Callable | None" = None,
) -> 'int | None'
Docstring:
Write records stored in a DataFrame to a SQL database.

Databases supported by SQLAlchemy [1]_ are supported. Tables can be
newly created, appended to, or overwritten.

Parameters
----------
name : str
    Name of SQL table.
con : sqlalchemy.engine.(Engine or Connection) or sqlite3.Connection
    Using SQLAlchemy makes it possible to use any DB supported by that
    library. Legacy support is provided for sqlite3.Connection objects. The user
    is responsible for engine disposal and connection closure for the SQLAlchemy
    connectable. See `here                 <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
    If passing a sqlalchemy.engine.Connection which is already in a transaction,
    the transaction will not be committed.  If passing a sqlite3.Connection,
    it will not be possible to roll back the record insertion.

schema : str, optional
    Specify the schema (if database flavor supports this). If None, use
    default schema.
if_exists : {'fail', 'replace', 'append'}, default 'fail'
    How to behave if the table already exists.

    * fail: Raise a ValueError.
    * replace: Drop the table before inserting new values.
    * append: Insert new values to the existing table.

index : bool, default True
    Write DataFrame index as a column. Uses `index_label` as the column
    name in the table.
index_label : str or sequence, default None
    Column label for index column(s). If None is given (default) and
    `index` is True, then the index names are used.
    A sequence should be given if the DataFrame uses MultiIndex.
chunksize : int, optional
    Specify the number of rows in each batch to be written at a time.
    By default, all rows will be written at once.
dtype : dict or scalar, optional
    Specifying the datatype for columns. If a dictionary is used, the
    keys should be the column names and the values should be the
    SQLAlchemy types or strings for the sqlite3 legacy mode. If a
    scalar is provided, it will be applied to all columns.
method : {None, 'multi', callable}, optional
    Controls the SQL insertion clause used:

    * None : Uses standard SQL ``INSERT`` clause (one per row).
    * 'multi': Pass multiple values in a single ``INSERT`` clause.
    * callable with signature ``(pd_table, conn, keys, data_iter)``.

    Details and a sample callable implementation can be found in the
    section :ref:`insert method <io.sql.method>`.

Returns
-------
None or int
    Number of rows affected by to_sql. None is returned if the callable
    passed into ``method`` does not return an integer number of rows.

    The number of returned rows affected is the sum of the ``rowcount``
    attribute of ``sqlite3.Cursor`` or SQLAlchemy connectable which may not
    reflect the exact number of written rows as stipulated in the
    `sqlite3 <https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.rowcount>`__ or
    `SQLAlchemy <https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.rowcount>`__.

    .. versionadded:: 1.4.0

Raises
------
ValueError
    When the table already exists and `if_exists` is 'fail' (the
    default).

See Also
--------
read_sql : Read a DataFrame from a table.

Notes
-----
Timezone aware datetime columns will be written as
``Timestamp with timezone`` type with SQLAlchemy if supported by the
database. Otherwise, the datetimes will be stored as timezone unaware
timestamps local to the original timezone.

References
----------
.. [1] https://docs.sqlalchemy.org
.. [2] https://www.python.org/dev/peps/pep-0249/

Examples
--------
Create an in-memory SQLite database.

>>> from sqlalchemy import create_engine
>>> engine = create_engine('sqlite://', echo=False)

Create a table from scratch with 3 rows.

>>> df = pd.DataFrame({'name' : ['User 1', 'User 2', 'User 3']})
>>> df
     name
0  User 1
1  User 2
2  User 3

>>> df.to_sql(name='users', con=engine)
3
>>> from sqlalchemy import text
>>> with engine.connect() as conn:
...    conn.execute(text("SELECT * FROM users")).fetchall()
[(0, 'User 1'), (1, 'User 2'), (2, 'User 3')]

An `sqlalchemy.engine.Connection` can also be passed to `con`:

>>> with engine.begin() as connection:
...     df1 = pd.DataFrame({'name' : ['User 4', 'User 5']})
...     df1.to_sql(name='users', con=connection, if_exists='append')
2

This is allowed to support operations that require that the same
DBAPI connection is used for the entire operation.

>>> df2 = pd.DataFrame({'name' : ['User 6', 'User 7']})
>>> df2.to_sql(name='users', con=engine, if_exists='append')
2
>>> with engine.connect() as conn:
...    conn.execute(text("SELECT * FROM users")).fetchall()
[(0, 'User 1'), (1, 'User 2'), (2, 'User 3'),
 (0, 'User 4'), (1, 'User 5'), (0, 'User 6'),
 (1, 'User 7')]

Overwrite the table with just ``df2``.

>>> df2.to_sql(name='users', con=engine, if_exists='replace',
...            index_label='id')
2
>>> with engine.connect() as conn:
...    conn.execute(text("SELECT * FROM users")).fetchall()
[(0, 'User 6'), (1, 'User 7')]

Use ``method`` to define a callable insertion method to do nothing
if there's a primary key conflict on a table in a PostgreSQL database.

>>> from sqlalchemy.dialects.postgresql import insert
>>> def insert_on_conflict_nothing(table, conn, keys, data_iter):
...     # "a" is the primary key in "conflict_table"
...     data = [dict(zip(keys, row)) for row in data_iter]
...     stmt = insert(table.table).values(data).on_conflict_do_nothing(index_elements=["a"])
...     result = conn.execute(stmt)
...     return result.rowcount
>>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append", method=insert_on_conflict_nothing)  # doctest: +SKIP
0

For MySQL, a callable to update columns ``b`` and ``c`` if there's a conflict
on a primary key.

>>> from sqlalchemy.dialects.mysql import insert
>>> def insert_on_conflict_update(table, conn, keys, data_iter):
...     # update columns "b" and "c" on primary key conflict
...     data = [dict(zip(keys, row)) for row in data_iter]
...     stmt = (
...         insert(table.table)
...         .values(data)
...     )
...     stmt = stmt.on_duplicate_key_update(b=stmt.inserted.b, c=stmt.inserted.c)
...     result = conn.execute(stmt)
...     return result.rowcount
>>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append", method=insert_on_conflict_update)  # doctest: +SKIP
2

Specify the dtype (especially useful for integers with missing values).
Notice that while pandas is forced to store the data as floating point,
the database supports nullable integers. When fetching the data with
Python, we get back integer scalars.

>>> df = pd.DataFrame({"A": [1, None, 2]})
>>> df
     A
0  1.0
1  NaN
2  2.0

>>> from sqlalchemy.types import Integer
>>> df.to_sql(name='integers', con=engine, index=False,
...           dtype={"A": Integer()})
3

>>> with engine.connect() as conn:
...   conn.execute(text("SELECT * FROM integers")).fetchall()
[(1,), (None,), (2,)]
Source:
    @final
    @deprecate_nonkeyword_arguments(
        version="3.0", allowed_args=["self", "name", "con"], name="to_sql"
    )
    def to_sql(
        self,
        name: str,
        con,
        schema: str | None = None,
        if_exists: Literal["fail", "replace", "append"] = "fail",
        index: bool_t = True,
        index_label: IndexLabel | None = None,
        chunksize: int | None = None,
        dtype: DtypeArg | None = None,
        method: Literal["multi"] | Callable | None = None,
    ) -> int | None:
        """
        Write records stored in a DataFrame to a SQL database.

        Databases supported by SQLAlchemy [1]_ are supported. Tables can be
        newly created, appended to, or overwritten.

        Parameters
        ----------
        name : str
            Name of SQL table.
        con : sqlalchemy.engine.(Engine or Connection) or sqlite3.Connection
            Using SQLAlchemy makes it possible to use any DB supported by that
            library. Legacy support is provided for sqlite3.Connection objects. The user
            is responsible for engine disposal and connection closure for the SQLAlchemy
            connectable. See `here \
                <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
            If passing a sqlalchemy.engine.Connection which is already in a transaction,
            the transaction will not be committed.  If passing a sqlite3.Connection,
            it will not be possible to roll back the record insertion.

        schema : str, optional
            Specify the schema (if database flavor supports this). If None, use
            default schema.
        if_exists : {'fail', 'replace', 'append'}, default 'fail'
            How to behave if the table already exists.

            * fail: Raise a ValueError.
            * replace: Drop the table before inserting new values.
            * append: Insert new values to the existing table.

        index : bool, default True
            Write DataFrame index as a column. Uses `index_label` as the column
            name in the table.
        index_label : str or sequence, default None
            Column label for index column(s). If None is given (default) and
            `index` is True, then the index names are used.
            A sequence should be given if the DataFrame uses MultiIndex.
        chunksize : int, optional
            Specify the number of rows in each batch to be written at a time.
            By default, all rows will be written at once.
        dtype : dict or scalar, optional
            Specifying the datatype for columns. If a dictionary is used, the
            keys should be the column names and the values should be the
            SQLAlchemy types or strings for the sqlite3 legacy mode. If a
            scalar is provided, it will be applied to all columns.
        method : {None, 'multi', callable}, optional
            Controls the SQL insertion clause used:

            * None : Uses standard SQL ``INSERT`` clause (one per row).
            * 'multi': Pass multiple values in a single ``INSERT`` clause.
            * callable with signature ``(pd_table, conn, keys, data_iter)``.

            Details and a sample callable implementation can be found in the
            section :ref:`insert method <io.sql.method>`.

        Returns
        -------
        None or int
            Number of rows affected by to_sql. None is returned if the callable
            passed into ``method`` does not return an integer number of rows.

            The number of returned rows affected is the sum of the ``rowcount``
            attribute of ``sqlite3.Cursor`` or SQLAlchemy connectable which may not
            reflect the exact number of written rows as stipulated in the
            `sqlite3 <https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.rowcount>`__ or
            `SQLAlchemy <https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.rowcount>`__.

            .. versionadded:: 1.4.0

        Raises
        ------
        ValueError
            When the table already exists and `if_exists` is 'fail' (the
            default).

        See Also
        --------
        read_sql : Read a DataFrame from a table.

        Notes
        -----
        Timezone aware datetime columns will be written as
        ``Timestamp with timezone`` type with SQLAlchemy if supported by the
        database. Otherwise, the datetimes will be stored as timezone unaware
        timestamps local to the original timezone.

        References
        ----------
        .. [1] https://docs.sqlalchemy.org
        .. [2] https://www.python.org/dev/peps/pep-0249/

        Examples
        --------
        Create an in-memory SQLite database.

        >>> from sqlalchemy import create_engine
        >>> engine = create_engine('sqlite://', echo=False)

        Create a table from scratch with 3 rows.

        >>> df = pd.DataFrame({'name' : ['User 1', 'User 2', 'User 3']})
        >>> df
             name
        0  User 1
        1  User 2
        2  User 3

        >>> df.to_sql(name='users', con=engine)
        3
        >>> from sqlalchemy import text
        >>> with engine.connect() as conn:
        ...    conn.execute(text("SELECT * FROM users")).fetchall()
        [(0, 'User 1'), (1, 'User 2'), (2, 'User 3')]

        An `sqlalchemy.engine.Connection` can also be passed to `con`:

        >>> with engine.begin() as connection:
        ...     df1 = pd.DataFrame({'name' : ['User 4', 'User 5']})
        ...     df1.to_sql(name='users', con=connection, if_exists='append')
        2

        This is allowed to support operations that require that the same
        DBAPI connection is used for the entire operation.

        >>> df2 = pd.DataFrame({'name' : ['User 6', 'User 7']})
        >>> df2.to_sql(name='users', con=engine, if_exists='append')
        2
        >>> with engine.connect() as conn:
        ...    conn.execute(text("SELECT * FROM users")).fetchall()
        [(0, 'User 1'), (1, 'User 2'), (2, 'User 3'),
         (0, 'User 4'), (1, 'User 5'), (0, 'User 6'),
         (1, 'User 7')]

        Overwrite the table with just ``df2``.

        >>> df2.to_sql(name='users', con=engine, if_exists='replace',
        ...            index_label='id')
        2
        >>> with engine.connect() as conn:
        ...    conn.execute(text("SELECT * FROM users")).fetchall()
        [(0, 'User 6'), (1, 'User 7')]

        Use ``method`` to define a callable insertion method to do nothing
        if there's a primary key conflict on a table in a PostgreSQL database.

        >>> from sqlalchemy.dialects.postgresql import insert
        >>> def insert_on_conflict_nothing(table, conn, keys, data_iter):
        ...     # "a" is the primary key in "conflict_table"
        ...     data = [dict(zip(keys, row)) for row in data_iter]
        ...     stmt = insert(table.table).values(data).on_conflict_do_nothing(index_elements=["a"])
        ...     result = conn.execute(stmt)
        ...     return result.rowcount
        >>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append", method=insert_on_conflict_nothing)  # doctest: +SKIP
        0

        For MySQL, a callable to update columns ``b`` and ``c`` if there's a conflict
        on a primary key.

        >>> from sqlalchemy.dialects.mysql import insert
        >>> def insert_on_conflict_update(table, conn, keys, data_iter):
        ...     # update columns "b" and "c" on primary key conflict
        ...     data = [dict(zip(keys, row)) for row in data_iter]
        ...     stmt = (
        ...         insert(table.table)
        ...         .values(data)
        ...     )
        ...     stmt = stmt.on_duplicate_key_update(b=stmt.inserted.b, c=stmt.inserted.c)
        ...     result = conn.execute(stmt)
        ...     return result.rowcount
        >>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append", method=insert_on_conflict_update)  # doctest: +SKIP
        2

        Specify the dtype (especially useful for integers with missing values).
        Notice that while pandas is forced to store the data as floating point,
        the database supports nullable integers. When fetching the data with
        Python, we get back integer scalars.

        >>> df = pd.DataFrame({"A": [1, None, 2]})
        >>> df
             A
        0  1.0
        1  NaN
        2  2.0

        >>> from sqlalchemy.types import Integer
        >>> df.to_sql(name='integers', con=engine, index=False,
        ...           dtype={"A": Integer()})
        3

        >>> with engine.connect() as conn:
        ...   conn.execute(text("SELECT * FROM integers")).fetchall()
        [(1,), (None,), (2,)]
        """  # noqa: E501
        from pandas.io import sql

        return sql.to_sql(
            self,
            name,
            con,
            schema=schema,
            if_exists=if_exists,
            index=index,
            index_label=index_label,
            chunksize=chunksize,
            dtype=dtype,
            method=method,
        )
File:      c:\users\computer\venvs\vanna\lib\site-packages\pandas\core\generic.py
Type:      method

In [9]:
results = execution_accuracy(fake_benchmark, fake_submission_df)

C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)
C:\Users\computer\AppData\Local\Temp\ipykernel_3256\979838441.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, con=READONLY_CON)

failed to execute
failed to execute